In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [3]:
###reading dataset
df=pd.read_csv('disaster_tweets_data.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'disaster_tweets_data.csv'

In [4]:
#removal of null values if present any
df.isnull().sum()  #since we are not having any null values we can neglet this section

tweets    0
target    0
dtype: int64

In [9]:
#removing patterns in input text
def remove_pattern(input_txt, pattern):
    r = re.findall(pattern, input_txt)
    for word in r:
        input_txt = re.sub(word, "", input_txt)
    return input_txt

In [11]:
df['processed_data'] = np.vectorize(remove_pattern)(df['tweets'], "#[\w]*")
df.head()

tweets  target  \
0  Our Deeds are the Reason of this #earthquake M...       1   
1             Forest fire near La Ronge Sask. Canada       1   
2  All residents asked to 'shelter in place' are ...       1   
3  13,000 people receive #wildfires evacuation or...       1   
4  Just got sent this photo from Ruby #Alaska as ...       1   

                                processed_tweet_data  \
0  Our Deeds are the Reason of this  May ALLAH Fo...   
1             Forest fire near La Ronge Sask. Canada   
2  All residents asked to 'shelter in place' are ...   
3  13,000 people receive  evacuation orders in Ca...   
4  Just got sent this photo from Ruby  as smoke f...   

                                      processed_data  
0  Our Deeds are the Reason of this  May ALLAH Fo...  
1             Forest fire near La Ronge Sask. Canada  
2  All residents asked to 'shelter in place' are ...  
3  13,000 people receive  evacuation orders in Ca...  
4  Just got sent this photo from Ruby  as smoke f...

In [12]:
#removing punctuations
# now we will remove all the special characters, punctuations and numbers
df['processed_data'] = df['processed_data'].str.replace("[^a-zA-Z#]", " ")
df.head()

/var/folders/h2/d4tmwpm94wd4gwgq55c1x1yw0000gn/T/ipykernel_31305/433836250.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['processed_data'] = df['processed_data'].str.replace("[^a-zA-Z#]", " ")


tweets  target  \
0  Our Deeds are the Reason of this #earthquake M...       1   
1             Forest fire near La Ronge Sask. Canada       1   
2  All residents asked to 'shelter in place' are ...       1   
3  13,000 people receive #wildfires evacuation or...       1   
4  Just got sent this photo from Ruby #Alaska as ...       1   

                                processed_tweet_data  \
0  Our Deeds are the Reason of this  May ALLAH Fo...   
1             Forest fire near La Ronge Sask. Canada   
2  All residents asked to 'shelter in place' are ...   
3  13,000 people receive  evacuation orders in Ca...   
4  Just got sent this photo from Ruby  as smoke f...   

                                      processed_data  
0  Our Deeds are the Reason of this  May ALLAH Fo...  
1             Forest fire near La Ronge Sask  Canada  
2  All residents asked to  shelter in place  are ...  
3         people receive  evacuation orders in Ca...  
4  Just got sent this photo from Ruby  as smoke f...

In [13]:
# converting all the  words to lower case
df['processed_data'].str.lower()

0       our deeds are the reason of this  may allah fo...
1                  forest fire near la ronge sask  canada
2       all residents asked to  shelter in place  are ...
3              people receive  evacuation orders in ca...
4       just got sent this photo from ruby  as smoke f...
                              ...                        
7608    two giant cranes holding a bridge collapse int...
7609     aria ahrary  thetawniest the out of control w...
7610    m            utc   km s of volcano hawaii  htt...
7611    police investigating after an e bike collided ...
7612    the latest  more homes razed by northern calif...
Name: processed_data, Length: 7613, dtype: object

In [14]:
# Tokenizing words
tokens = df['processed_data'].apply(lambda x: x.split())
tokens.head()

0    [Our, Deeds, are, the, Reason, of, this, May, ...
1        [Forest, fire, near, La, Ronge, Sask, Canada]
2    [All, residents, asked, to, shelter, in, place...
3    [people, receive, evacuation, orders, in, Cali...
4    [Just, got, sent, this, photo, from, Ruby, as,...
Name: processed_data, dtype: object

In [30]:
#Removing Stop words
import nltk
from nltk.corpus import stopwords
nltk.download("stopwords")

sw = stopwords.words('English')

re_sw = [i for i in df['processed_data'] if i not in sw]
print(re_sw)


['Our Deeds are the Reason of this  May ALLAH Forgive us all', 'Forest fire near La Ronge Sask  Canada', 'All residents asked to  shelter in place  are being notified by officers  No other evacuation or shelter in place orders are expected', '       people receive  evacuation orders in California ', 'Just got sent this photo from Ruby  as smoke from  pours into a school ', ' Update    California Hwy     closed in both directions due to Lake County fire    ', '  Heavy rain causes flash flooding of streets in Manitou  Colorado Springs areas', 'I m on top of the hill and I can see a fire in the woods   ', 'There s an emergency evacuation happening now in the building across the street', 'I m afraid that the tornado is coming to our area   ', 'Three people died from the heat wave so far', 'Haha South Tampa is getting flooded hah  WAIT A SECOND I LIVE IN SOUTH TAMPA WHAT AM I GONNA DO WHAT AM I GONNA DO FVCK ', '        or    days  I ve lost count ', ' in Bago Myanmar  arrived Bago', 'Damag

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/jsnagavishnusai/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [39]:
#Stemming or lemmatizing the words

from nltk.stem import PorterStemmer, LancasterStemmer, WordNetLemmatizer
ps = PorterStemmer() 
lm= WordNetLemmatizer()

#Stemming
stem_ps = [ps.stem(i) for i in df['processed_data']]
print(stem_ps)

['our deeds are the reason of this  may allah forgive us al', 'forest fire near la ronge sask  canada', 'all residents asked to  shelter in place  are being notified by officers  no other evacuation or shelter in place orders are expect', '       people receive  evacuation orders in california ', 'just got sent this photo from ruby  as smoke from  pours into a school ', ' update    california hwy     closed in both directions due to lake county fire    ', '  heavy rain causes flash flooding of streets in manitou  colorado springs area', 'i m on top of the hill and i can see a fire in the woods   ', 'there s an emergency evacuation happening now in the building across the street', 'i m afraid that the tornado is coming to our area   ', 'three people died from the heat wave so far', 'haha south tampa is getting flooded hah  wait a second i live in south tampa what am i gonna do what am i gonna do fvck ', '        or    days  i ve lost count ', ' in bago myanmar  arrived bago', 'damage to

LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet

  Searched in:
    - '/Users/jsnagavishnusai/nltk_data'
    - '/Users/jsnagavishnusai/anaconda3/nltk_data'
    - '/Users/jsnagavishnusai/anaconda3/share/nltk_data'
    - '/Users/jsnagavishnusai/anaconda3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


In [46]:
#lemmatizing
nltk.download('wordnet')
nltk.download('omw-1.4')
lem = [lm.lemmatize(i) for i in df['processed_data']]
print(lem)

['Our Deeds are the Reason of this  May ALLAH Forgive us all', 'Forest fire near La Ronge Sask  Canada', 'All residents asked to  shelter in place  are being notified by officers  No other evacuation or shelter in place orders are expected', '       people receive  evacuation orders in California ', 'Just got sent this photo from Ruby  as smoke from  pours into a school ', ' Update    California Hwy     closed in both directions due to Lake County fire    ', '  Heavy rain causes flash flooding of streets in Manitou  Colorado Springs areas', 'I m on top of the hill and I can see a fire in the woods   ', 'There s an emergency evacuation happening now in the building across the street', 'I m afraid that the tornado is coming to our area   ', 'Three people died from the heat wave so far', 'Haha South Tampa is getting flooded hah  WAIT A SECOND I LIVE IN SOUTH TAMPA WHAT AM I GONNA DO WHAT AM I GONNA DO FVCK ', '        or    days  I ve lost count ', ' in Bago Myanmar  arrived Bago', 'Damag

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/jsnagavishnusai/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/jsnagavishnusai/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [52]:
#Count Vectorizer
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
res_cv = cv.fit_transform(df['processed_data']).toarray()
print(cv.get_feature_names_out())
print(len(cv.get_feature_names_out()))

['aa' 'aaaa' 'aaaaaaallll' ... 'zzuz' 'zzweeezjug' 'zzzz']
20995


In [53]:
print(res_cv)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [162]:
# 5th step

x = res_cv
y = df['target']
print(type(x))
print(type(y))
print(x.shape)
print(y.shape)


<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>
(7613, 20995)
(7613,)


In [163]:
# #Spliting data into training and test data.

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(5709, 20995)
(1904, 20995)
(5709,)
(1904,)


In [ ]:
#Multinomial Naïve Bayes Classification

In [164]:
from sklearn.naive_bayes import MultinomialNB

m1=MultinomialNB()
m1.fit(x_train,y_train)

MultinomialNB()

In [165]:
ypred_m1 = m1.predict(x_test)
ypred_m1

array([0, 0, 1, ..., 1, 0, 1])

In [166]:
from sklearn.metrics import confusion_matrix, classification_report

print("Confusion Matrix - Multinomial Naive Bayes:")
print(confusion_matrix(y_test,ypred_m1))
print("Classification Report - Multinomial Naive Bayes:")
print(classification_report(y_test, ypred_m1))

nb = accuracy_score(y_test,ypred_m1)
print(' Multinomial Naive Bayes Accuracy Score: ',nb)

Confusion Matrix - Multinomial Naive Bayes:
[[934 157]
 [217 596]]
Classification Report - Multinomial Naive Bayes:
              precision    recall  f1-score   support

           0       0.81      0.86      0.83      1091
           1       0.79      0.73      0.76       813

    accuracy                           0.80      1904
   macro avg       0.80      0.79      0.80      1904
weighted avg       0.80      0.80      0.80      1904

 Multinomial Naive Bayes Accuracy Score:  0.8035714285714286


In [ ]:
#Logistic Regression

In [167]:
from sklearn.linear_model import LogisticRegression

m2 = LogisticRegression()
m2.fit(x_train,y_train)

LogisticRegression()

In [168]:
ypred_m2 = m2.predict(x_test)
ypred_m2

array([0, 0, 1, ..., 1, 0, 0])

In [169]:
print("Confusion Matrix - Logistic Regression:")
print(confusion_matrix(y_test, ypred_m2))
print("Classification Report - Logistic Regression:")
print(classification_report(y_test, ypred_m2))

knn = accuracy_score(y_test,ypred_m2)
print(' KNN Classifier Accuracy Score: ',knn)

Confusion Matrix - Logistic Regression:
[[950 141]
 [230 583]]
Classification Report - Logistic Regression:
              precision    recall  f1-score   support

           0       0.81      0.87      0.84      1091
           1       0.81      0.72      0.76       813

    accuracy                           0.81      1904
   macro avg       0.81      0.79      0.80      1904
weighted avg       0.81      0.81      0.80      1904

 KNN Classifier Accuracy Score:  0.8051470588235294


In [ ]:
#KNN Classification

In [170]:
from sklearn.neighbors import KNeighborsClassifier

m3 = KNeighborsClassifier()
m3.fit(x_train,y_train)

KNeighborsClassifier()

In [171]:
ypred_m3 = m3.predict(x_test)
ypred_m3

array([0, 0, 0, ..., 0, 0, 0])

In [172]:
print("Confusion Matrix - KNN Classification:")
print(confusion_matrix(y_test, ypred_m3))
print("Classification Report - KNN Classification:")
print(classification_report(y_test, ypred_m3))

lr = accuracy_score(y_test,ypred_m3)
print(' Logistic Regression Accuracy Score: ',lr)

Confusion Matrix - KNN Classification:
[[1071   20]
 [ 588  225]]
Classification Report - KNN Classification:
              precision    recall  f1-score   support

           0       0.65      0.98      0.78      1091
           1       0.92      0.28      0.43       813

    accuracy                           0.68      1904
   macro avg       0.78      0.63      0.60      1904
weighted avg       0.76      0.68      0.63      1904

 Logistic Regression Accuracy Score:  0.680672268907563


In [174]:
print('Multinomial Naive Bayes Accuracy : ',nb*100)
print('Logistic Regression Accuracy : ',lr*100)
print('KNN Classifier Accuracy : ',knn*100)

Multinomial Naive Bayes Accuracy :  80.35714285714286
Logistic Regression Accuracy :  68.0672268907563
KNN Classifier Accuracy :  80.51470588235294


In [ ]:
print('Therefore the BEST model with BEST accuracy is KNN Classification')